# Generated by Django 5.0.3 on 2024-04-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='order')),
                ('icon', models.ImageField(upload_to='contact/icons/', verbose_name='icon')),
                ('contact', models.CharField(max_length=255, verbose_name='contact')),
            ],
            options={
                'verbose_name': 'Contact ',
                'verbose_name_plural': '9 Contacts',
                'db_table': 'contact',
                'ordering': ('order',),
            },
        ),
    ]
