# Generated by Django 5.0.3 on 2024-04-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('sub_title', models.CharField(max_length=255, verbose_name='sub title')),
                ('cover', models.ImageField(upload_to='news/cover/')),
                ('slug', models.SlugField(max_length=255, verbose_name='slug')),
                ('text', models.TextField(verbose_name='text')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'db_table': 'news',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('sub_title', models.CharField(max_length=255, verbose_name='sub title')),
                ('text', models.TextField(verbose_name='text')),
            ],
            options={
                'verbose_name': 'Static Page ',
                'verbose_name_plural': 'Static Pages',
                'db_table': 'static_page',
                'ordering': ('-created_at',),
            },
        ),
    ]
