# Generated by Django 5.0.3 on 2024-04-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='order')),
                ('icon', models.ImageField(upload_to='statistic/icon/', verbose_name='icon')),
                ('url', models.URLField(max_length=255, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Partner ',
                'verbose_name_plural': '4 Partners',
                'db_table': 'partner',
                'ordering': ('order',),
            },
        ),
    ]
