# Generated by Django 5.0.3 on 2024-04-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('certificate', models.ImageField(upload_to='company_certificate/images/', verbose_name='certificate')),
                ('sub_title', models.CharField(max_length=255, verbose_name='sub_title')),
                ('text', models.TextField(verbose_name='text')),
            ],
            options={
                'verbose_name': 'Company Certificate ',
                'verbose_name_plural': '6 Company Certificates',
                'db_table': 'company_certificate',
            },
        ),
    ]
