# Generated by Django 5.0.3 on 2024-04-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='First',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='order')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('sub_title', models.CharField(max_length=255, verbose_name='description')),
                ('image', models.ImageField(upload_to='slider/image/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Slider ',
                'verbose_name_plural': '2 Sliders',
                'db_table': 'slider',
                'ordering': ('order',),
            },
        ),
    ]
